### PR TITLE
Added --no-coverage flag to `skyux watch`

### PR DESCRIPTION
**Pull request by Blackbaud-SteveBrush**
**How to test:**
- Type `skyux watch --no-coverage` <-- instrument loader will not mangle the source files

Addresses [issue #643](https://github.com/blackbaud/skyux2/issues/643)

### CODE REVIEW

**Comment by Blackbaud-BobbyEarl** [comment]
Any thoughts on putting `argv` as the second argument to the `getWebpackConfig()` method?

**Comment by Blackbaud-SteveBrush** [comment]
@Blackbaud-BobbyEarl:
- Having `argv` as the first parameter seemed to be following the convention of the other CLI commands: https://github.com/blackbaud/skyux-builder/blob/master/index.js#L12. Willing to change it if you prefer it; just wanted to let you know why I chose to put it first.
- I'll work on simplifying it. When typing `skyux watch --no-coverage`, the flag gets passed in as `'coverage', false`, which makes it difficult...

**Comment by Blackbaud-SteveBrush** [comment]
- I was following a previous convention: https://github.com/blackbaud/skyux-builder/blob/master/cli/serve.js#L42. (Happy to move `argv` to the second-place argument, if desired.)
- I'll work on simplifying.

**Comment by blackbaud-johnly** [comment]
I created https://github.com/blackbaud/skyux2/issues/723 to document this option. Thanks @Blackbaud-BobbyEarl

**Pull request merged**
