### PR TITLE
Feature generate modal

### PR DESCRIPTION
**Pull request by Blackbaud-BryonWilkins**

### CODE REVIEW

**Comment by Blackbaud-BobbyEarl** [comment]
Hey @Blackbaud-BryonWilkins, just a reminder there are a few linting errors / tests failing that make reviewing this a little more difficult.

**Comment by Blackbaud-TrevorBurch** [comment]
@Blackbaud-BryonWilkins doing some housekeeping and we came across this from late 2017. Are you interested in fixing this or should we just close this PR?

**Comment by Blackbaud-BryonWilkins** [comment]
Yea I would say, I'm no longer working on this.
________________________________

**Comment by Blackbaud-TrevorBurch** [comment]
Closing due to inactivity

**Pull request closed without merging**
