### PR TITLE
[HOLD] Removed flag for SkyAuthHttp injection.

### PR DESCRIPTION
**Pull request by blackbaud-brandonhare**
I made this PR to spark some discussion. Steve and I have discussed this already, but Bobby, I wanted to get your input. I'll grab you once you get in.

### CODE REVIEW

**Comment by Blackbaud-BobbyEarl** [comment]
In order to keep things documented can you add a little context around this change? What’s the scenario where you’re always needing `SkyAuthHttp` provided?

**Comment by blackbaud-brandonhare** [comment]
For my specific use case, I'm using it in my SearchResultsProvider to make requests to my Stache Search Query endpoint. That query conditionally requires the request to be authenticated depending on the status of the site (internal or public). The problem is, if Auth is set to false, the SkyAuthHttp provider doesn't get injected, and it will crash any Stache site that uses the new provider, which will be all of them. I'm not certain this is the ideal approach, but I wanted to create the PR just so we could discuss it further.

**Comment by blackbaud-brandonhare** [comment]
Hmm. I actually found a better solution in my provider. Closing this.

**Comment by Blackbaud-BobbyEarl** [comment]
The other solution not work out @blackbaud-brandonhare?

**Comment by blackbaud-brandonhare** [comment]
It does @Blackbaud-BobbyEarl, but @Blackbaud-SteveBrush wanted me to reopen it for discussion about the SkyAuthHttp and Http in general. I can close it if we want to take that elsewhere.

**Comment by Blackbaud-BobbyEarl** [comment]
Nah fine by me to leave it open.  Let's discuss away.  :-)

**Comment by Blackbaud-SteveBrush** [comment]
Related: https://github.com/blackbaud/skyux2/issues/1252

If the library wishes to use `SkyAuthHttp` (and even provide it statically through their own service), it won't work because the auth http service is never provided (unless `auth=true` in **skyuxconfig.json**). This essentially makes `SkyAuthHttp` unusable in component libraries.

@Blackbaud-BobbyEarl: I vote to merge this in, if possible, to allow libraries to use `SkyAuthHttp` in their implementations regardless of the `auth` setting.

**Comment by Blackbaud-SteveBrush** [comment]
@blackbaud-brandonhare Something I just thought about: curious if this will affect the auto-redirect to the login endpoint?

**Comment by blackbaud-brandonhare** [comment]
@Blackbaud-SteveBrush Hmm. That's a good question. It's worth investigating that.

**Comment by blackbaud-brandonhare** [comment]
@Blackbaud-SteveBrush I just ran `e2e` and everything worked as expected, so I think we're good Steve.

**Comment by Blackbaud-SteveBrush** [comment]
Let's close this until we've figured out how we want libraries to consume the `runtime` directory.

**Pull request closed without merging**
